// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK3U_OIEnfrrI28Xz4b993Cn9ZVe6AxDg',
    appId: '1:18524079250:web:a85d99a9a24bc39a5c124b',
    messagingSenderId: '18524079250',
    projectId: 'practice522-8bd02',
    authDomain: 'practice522-8bd02.firebaseapp.com',
    storageBucket: 'practice522-8bd02.appspot.com',
    measurementId: 'G-VETF0Z2LNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACHGY8iwA5PmQDYe0YSkhWmEexekzZxSQ',
    appId: '1:18524079250:android:f0c445289f1b546c5c124b',
    messagingSenderId: '18524079250',
    projectId: 'practice522-8bd02',
    storageBucket: 'practice522-8bd02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOoJBVw4eoO9U9b0cTVJikYjb9uepsrEk',
    appId: '1:18524079250:ios:deb0bce60ad002c85c124b',
    messagingSenderId: '18524079250',
    projectId: 'practice522-8bd02',
    storageBucket: 'practice522-8bd02.appspot.com',
    iosBundleId: 'com.example.JihyunYTiktocCameraTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOoJBVw4eoO9U9b0cTVJikYjb9uepsrEk',
    appId: '1:18524079250:ios:2934ea7d02e760b75c124b',
    messagingSenderId: '18524079250',
    projectId: 'practice522-8bd02',
    storageBucket: 'practice522-8bd02.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK3U_OIEnfrrI28Xz4b993Cn9ZVe6AxDg',
    appId: '1:18524079250:web:db2ed9411aa5cdb25c124b',
    messagingSenderId: '18524079250',
    projectId: 'practice522-8bd02',
    authDomain: 'practice522-8bd02.firebaseapp.com',
    storageBucket: 'practice522-8bd02.appspot.com',
    measurementId: 'G-TQZP6L069R',
  );
}
